### ISSUE TITLE
nbdev_prepare TypeError exception when parsing pycaret import

### ISSUE THREAD

**Issue by castorfou** [fastai/nbdev#1150] opened 2022-10-07 08:01 UTC
not 100% sure this is due to nbdev.

With this simple cell:
```python
#| export
from pycaret.regression import RegressionExperiment
```
`nbdev_prepare` or `nbdev_docs` fails with the folowwing stacktrace:

```
(pycaret_nbdev) explore@explore-ThinkPad-P53:~/git/guillaume/pycaret_nbdev$ nbdev_prepare 
TypeError in /home/explore/git/guillaume/pycaret_nbdev/nbs/index.ipynb:
===========================================================================

While Executing Cell #2:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from pycaret_nbdev.core import *

File ~/git/guillaume/pycaret_nbdev/pycaret_nbdev/core.py:7, in <module>
      4 __all__ = ['foo']
      6 # %% ../nbs/00_core.ipynb 3
----> 7 from pycaret.regression import RegressionExperiment
      9 # %% ../nbs/00_core.ipynb 4
     10 def foo(): pass

[....]

File ~/miniconda3/envs/pycaret_nbdev/lib/python3.9/site-packages/IPython/core/magics/pylab.py:99, in PylabMagics.matplotlib(self, line)
     97     print("Available matplotlib backends: %s" % backends_list)
     98 else:
---> 99     gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
    100     self._show_matplotlib_backend(args.gui, backend)

TypeError: enable_matplotlib() takes 1 positional argument but 2 were given


nbdev Tests Failed On The Following Notebooks:
==================================================
        00_core.ipynb
        index.ipynb
```

it looks like this call gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
is analysed as providing 2 arguments (due to ','?)

I have setup a minimalist repo to illustrate:
https://github.com/castorfou/pycaret_nbdev

Just a plain new repo with nbdev_new and just added this pycaret import into 00_core.ipynb

As a workaround, I have tried with skip_exec: true in frontmatter. It works locally but not in CI/D (using gitlab not gh)

**Comment by seeM** [comment] 2022-10-18 06:18
I think this is caused by an upstream issue tracked in https://github.com/fastai/execnb/issues/42. That should be fixed by https://github.com/fastai/execnb/pull/43.

**Comment by seeM** [comment] 2022-10-18 06:19
I'll close this in the meantime and reopen if needed.

**Closed by seeM** 2022-10-18 06:19 UTC

**Comment by seeM** [comment] 2023-02-12 08:28
@jph00 could we please get an execnb release for https://github.com/fastai/execnb/pull/43?

**Comment by jph00** [comment] 2023-02-13 00:37
> @jph00 could we please get an execnb release for [fastai/execnb#43](https://github.com/fastai/execnb/pull/43)?

Absolutely! :)
