### ISSUE TITLE
IPython.display.Image(embed=True) results in incorrect image reference in GitHub Pages

### ISSUE THREAD

**Issue by tylere** [fastai/nbdev#924] opened 2022-08-23 19:03 UTC
## To reproduce:

1. Add a code block that embeds an image from a remote URL.
```
from IPython.display import Image
Image(url="https://avatars.githubusercontent.com/u/20547620", format='png', embed=True)
```

2. Note that it renders correctly when using nbdev_preview:
![Screen Shot 2022-08-23 at 11 50 24 AM](https://user-images.githubusercontent.com/92862/186240724-56fcaaf3-6aa7-4455-a480-0d5cdc10592a.png)

3. After pushing to GitHub, the image links are broken:
![Screen Shot 2022-08-23 at 11 50 48 AM](https://user-images.githubusercontent.com/92862/186240834-9e4d3df0-2bc4-449d-a492-d872d1fecb7d.png)

The HTML page references a /figure-**html** folder:
`github.io/.../index_files/figure-html/cell-11-output-1.png`

while the actual location of the file is in a /figure-**gfm** folder:
`github.io/.../index_files/figure-gfm/cell-11-output-1.png`

**Comment by hamelsmu** [comment] 2022-08-24 04:58
I tried really hard to reproduce this issue but could not:

repo: https://github.com/hamelsmu/nbdev-minimal/blob/main/00_core.ipynb
website: https://hamelsmu.github.io/nbdev-minimal/core.html

In the future, I recommend making a minimal repo that isolates the exact problem you are trying to report, as I've found that it often allows me to see the real issue.  In your case, their could be a different issue, but I cannot guess what that is unfortunately.  

Thank you, closing this issue

**Comment by hamelsmu** [comment] 2022-08-24 05:12
Actually!  My apologies, I think my comment came across too harsh 🙇🏽  I didn't mean it this way at all.

Let me reopen this issue because I want to solve this issue.  I also edited my message above to reflect more of what I was trying to say

**Comment by tylere** [comment] 2022-08-24 05:15
No worries. I will try to reproduce the issue in a simplified repo and report back.

**Comment by tylere** [comment] 2022-08-24 17:38
I am able to reproduce this issue in a minimal repo.
repo: https://github.com/tylere/test-image-embed
website: https://tylere.github.io/test-image-embed/
screenshot: 
![Screen Shot 2022-08-24 at 10 17 31 AM](https://user-images.githubusercontent.com/92862/186482042-ac5f1b2b-de68-4a5b-9e95-b69783b2c1ad.png)

This broken image references the /file-html directory:
https://tylere.github.io/test-image-embed/index_files/figure-html/cell-3-output-1.png

Given that you were not able to reproduce the issue, I may have something different in my development environment. I am using a conda enviroment, configured as follows:

1. `conda create -n test-image-embed  -c conda-forge -c fastai python=3.10 gh jupyterlab jupyterlab-git ghapi nbdev`
2. `conda activate test-image-embed`
3. `cd test-image-embed`
4. `nbdev_new`
5. `nbdev_install_hooks`
6. `jupyter lab`

Here is are the packages/versions installed in the environment:

```
(test-image-embed) tylere-macbookpro5:test-image-embed tylere$ conda list

# packages in environment at /Users/tylere/miniconda3/envs/test-image-embed:
#
# Name                    Version                   Build  Channel
anyio                     3.6.1              pyhd8ed1ab_1    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h1961e1f_2    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310h1961e1f_1004    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2022.6.15            h033912b_0    conda-forge
certifi                   2022.6.15       py310h2ec42d9_0    conda-forge
cffi                      1.15.1          py310h96bbf6e_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              37.0.4          py310h52c3658_0    conda-forge
debugpy                   1.6.3           py310h154be8b_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
execnb                    0.1.2                      py_0    fastai
executing                 0.10.0             pyhd8ed1ab_0    conda-forge
fastcore                  1.5.21             pyhd8ed1ab_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
gh                        2.14.6               h990441c_0    conda-forge
ghapi                     1.0.1              pyhd8ed1ab_0    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
icu                       70.1                 h96cf925_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4          py310h2ec42d9_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.15.1             pyh736e0ef_0    conda-forge
ipython                   8.4.0           py310h2ec42d9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.14.0             pyhd8ed1ab_0    conda-forge
jupyter-server-mathjax    0.2.6              pyhc268e32_0    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1          py310h2ec42d9_0    conda-forge
jupyter_server            1.18.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.4.5              pyhd8ed1ab_0    conda-forge
jupyterlab-git            0.39.0             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.15.1             pyhd8ed1ab_0    conda-forge
libcxx                    14.0.6               hce7ea42_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsqlite                 3.39.2               h5a3d3bf_1    conda-forge
libxml2                   2.9.14               hea49891_4    conda-forge
libxslt                   1.1.35               heaa0ce8_0    conda-forge
libzlib                   1.2.12               hfe4f2af_2    conda-forge
lxml                      4.9.1           py310h6c45266_0    conda-forge
markupsafe                2.1.1           py310h1961e1f_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
nbclassic                 0.4.3              pyhd8ed1ab_0    conda-forge
nbclient                  0.6.7              pyhd8ed1ab_0    conda-forge
nbconvert                 7.0.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.0.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.0.0              pyhd8ed1ab_0    conda-forge
nbdev                     2.2.6                      py_0    fastai
nbdime                    3.1.1              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1q               hfe4f2af_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandoc                    2.19.2               h694c41f_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
psutil                    5.9.1           py310h6c45266_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1          py310h1961e1f_1    conda-forge
pysocks                   1.7.1           py310h2ec42d9_5    conda-forge
python                    3.10.6          ha7b0be1_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h1961e1f_4    conda-forge
pyzmq                     23.2.1          py310hcabbbd4_0    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                65.2.0          py310h2ec42d9_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
sniffio                   1.2.0           py310h2ec42d9_3    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
stack_data                0.4.0              pyhd8ed1ab_0    conda-forge
terminado                 0.15.0          py310h2ec42d9_0    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   6.2             py310h6c45266_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.3.3              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
```

**Comment by hamelsmu** [comment] 2022-08-24 18:01
Thanks @tylere can you confirm what version of Quarto you are running `quarto -V`

**Comment by tylere** [comment] 2022-08-24 19:02
(earthengine-jupyter) tylere-macbookpro5:earthengine-jupyter tylere$ quarto -V
1.0.38

**Comment by hamelsmu** [comment] 2022-08-24 19:05
@tylere can you try upgrading to the latest quarto with `nbdev_install`, does that make a difference?  The version you have is quite old so just want to rule that out

**Comment by hamelsmu** [comment] 2022-08-24 22:44
yes this has to do with the fact that your library name is different than your repo name.  This is a regression which I'll fix shortly

cc: @seeM

**Closed** 2022-08-25 20:58 UTC
Labels: bug
