### ISSUE TITLE
conda install -c fastai nbdev is not installing the last version on nvdev

### ISSUE THREAD

**Issue by HDavidEspinosa** [fastai/nbdev#452] opened 2021-04-01 23:29 UTC
I have done the conda install in Windows 10 and Ubuntu through WSL.

After installing on different environments multiple times, using the CLI

`conda install -c fastai nbdev`

I have to report that every time I got nbdev 0.2.4 installed and I could not find any way to update the version using conda or pip. 

The only way I was able to get the latest version was by cloning the repo and doing a 

`pip install -e .`

My main concern is that I have to keep an eye on the repo to get the latest update instead of using the package manager.

I am using conda 4.9.2 and pip 21.0.1 , in case that helps.

Am I doing something wrong? Might there be a problem with pip and conda releases?

**Comment by barrypj** [comment] 2021-04-02 10:32
I had the same issue.  See [https://github.com/fastai/nbdev/issues/451](url) for my conda-based solution/workaround.

**Comment by hamelsmu** [comment] 2021-04-03 04:29
This issue is a duplicate of #436

**Closed by hamelsmu** 2021-04-03 04:29 UTC
