### ISSUE TITLE
`nbdev_preview` && `nbdev_docs` not working on Apple M1

### ISSUE THREAD

**Issue by Isaac-Flath** [fastai/nbdev#1040] opened 2022-09-12 20:22 UTC
@seeM @jph00 @hamelsmu 

I believe this recreates an issue hamel was having.  Here's the details from when Hamel and I chatted and recreated his issue.

# Environment
+ Quarto Version: 1.2.94
+ Python Version: 3.9.7
+ System:  Apple M1 Pro chip |  Mac Os Monterey Version 12.2.1

# Setup
+ Updated execnb, ghapi, fastcore from master.  
+ install editable dev install of nbdev
+ Install [Quarto Pre-Release](https://quarto.org/docs/download/prerelease.html)

# Repro

`nbdev_docs` and `nbdev_preview` both fail for the same reason, here's the errrors.

```bash
(base) ✔ ~/github/fastai/nbdev [master|✔] 
15:50 $ nbdev_docs 
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:554 block_for_offset)
/usr/local/bin/quarto: line 145: 45068 Trace/BPT trap: 5       "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"
```

```bash
(base) ✔ ~/github/fastai/nbdev [master|✔] 
15:49 $ nbdev_preview
Preparing to preview
[ 1/33] explanations/docs.ipynb
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:554 block_for_offset)
/usr/local/bin/quarto: line 145: 44891 Trace/BPT trap: 5       "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"
```

# Minimal Repo

I tested using a repo that hamel created [tquarto](https://github.com/hamelsmu/tquarto/blob/main/run_quarto.py) and it worked as expected with the command `quarto preview`, but it failed when running `quarto preview`  with `subprocess` in python.

```bash
(base) ✔ ~/github/hamel/tquarto [main|✔] 
15:52 $ python run_quarto.py 
Preparing to preview
[1/2] index.qmd
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:554 block_for_offset)
/usr/local/bin/quarto: line 145: 45248 Trace/BPT trap: 5       "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"
```

```bash
(base) ✔ ~/github/hamel/tquarto [main|✔] 
15:53 $ quarto preview
Terminating existing preview server....DONE

Preparing to preview
[1/2] index.qmd
[2/2] test.ipynb

Watching files for changes
Browse at http://localhost:7167/
GET: /
GET: /test.html
GET: /
GET: /
```

**Comment by hamelsmu** [comment] 2022-09-12 20:27
Thanks @Isaac-Flath 🙌🏽 for pairing with me and reproducing the issue I have been facing.  

I am reasonably confident that I have isolated this issue to quarto running in a subprocess, I have created [a minimal project](https://github.com/hamelsmu/tquarto) that demonstrates this.  

## To Reproduce The Error

### Step 1: Clone the minimal example

```bash
git clone https://github.com/hamelsmu/tquarto.git && cd tquarto
```

### Step 2: Run quarto through a subprocess

(You should look at the contents of this file, it is just two lines of code)

```bash
python run_quarto.py
```

### Step 3: Navigate to the /test.html page (which is also on the navbar)

The Error we get:

```
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
/usr/local/bin/quarto: line 145:  9849 Trace/BPT trap: 5       "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"
```

If you don't get an error the first time, you can try this multiple time and eventually get an error.  I've also reproducd this on other machines.

## Info about my system:

- OS: MacOS Monterey 12.5.1, Apple M1 Pro
- Quarto Version `1.2.92`

##  Observations

- Running `quarto docs` or `quarto preview` does **not** produce the error
- The error only occurs when I run quarto through a subprocess by running `python run_quarto.py`
- The error mostly occurs when I navigate to the page generated by the notebook (i.e. `test.html`), but sometimes also occurs on server start as I think sometimes it tries to open that page directly
- I don't believe it has anything to do with the watchdog process, as I am able to repro the error with just `subprocess.run`
- I was able to repro this issue on a M1 Mac server which is a fresh/brand new environment

With nbdev, I'm able to make things work manually by doing the following steps:

1. comment out `subprocess.run` in `nbdev.quarto.nbdev_preview`
2. run `nbdev_preview` which whill generate a `_proc/` folder
3. cd into the `_proc/` folder and run `quarto preview`

This works without issue.  Again, when I introduce the subprocess that is when this error appears.  I have not opened an issue on the Quarto repo as quarto is working fine otherwise, its just this subprocess that seems to be causing things to fail, so I want to discuss this here with @jph00 and @seem to brainstorm any other ideas before submitting an issue to Quarto.

## Other information

I [recorded this video](https://www.loom.com/share/f591eb6972be45cbbfbb5e326a7a5f88) with additional commentary incase that is helpful

**Comment by hamelsmu** [comment] 2022-09-13 00:20
Tracking the Quarto issue here https://github.com/quarto-dev/quarto-cli/issues/2420

**Comment by hamelsmu** [comment] 2022-09-13 19:28
This has been closed via https://github.com/quarto-dev/quarto-cli/issues/2420


v1.2.101 has the fix: https://quarto.org/docs/download/prerelease.html

**Closed by hamelsmu** 2022-09-13 19:28 UTC
Labels: bug
