### ISSUE TITLE
FileNotFoundError unhelpful error message

### ISSUE THREAD

**Issue by DmitriyG228** [fastai/nbdev#128] opened 2020-04-09 17:46 UTC
hi, it would be helpful to have the file name in the error report that is causing the following issue while `notebook2script()`:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-ec1767d147e7> in <module>
      1 from nbdev.export import notebook2script
----> 2 notebook2script()

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/export.py in notebook2script(fname, silent, to_dict)
    369     else: files = glob.glob(fname)
    370     d = collections.defaultdict(list) if to_dict else None
--> 371     for f in sorted(files): d = _notebook2script(f, silent=silent, to_dict=d)
    372     if to_dict: return d
    373     else: add_init(Config().lib_path)

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/export.py in _notebook2script(fname, silent, to_dict)
    308         extra,code = extra_add(code)
    309         if a:
--> 310             if to_dict is None: _add2add(fname_out, [f"'{f}'" for f in names if '.' not in f and len(f) > 0] + extra)
    311         mod.index.update({f: fname.name for f in names})
    312         code = re.sub(r' +$', '', code, flags=re.MULTILINE)

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/nbdev/export.py in _add2add(fname, names, line_width)
    194 def _add2add(fname, names, line_width=120):
    195     if len(names) == 0: return
--> 196     with open(fname, 'r', encoding='utf8') as f: text = f.read()
    197     tw = TextWrapper(width=120, initial_indent='', subsequent_indent=' '*11, break_long_words=False)
    198     re_all = _re__all__def.search(text)

FileNotFoundError: [Errno 2] No such file or directory: '/home/dima/ab_nbdev/ab_nbdev/None.py'

**Comment by DmitriyG228** [comment] 2020-04-09 17:58
btw, I was able to find the causing file like that:
`files=[file for file in Path('.').ls() if 'ipynb' in file.name]

for file in files:
    print('--',file)
    notebook2script(file.name)`

**Comment by sgugger** [comment] 2020-04-09 21:19
I don't understand what bug you are reporting / what feature you are asking for. Could you be more specific?

**Comment by sgugger** [comment] 2020-04-15 12:09
Closing since there has not been an answer in a while. Please reopen with something clearer and a reproducer.

**Closed by sgugger** 2020-04-15 12:09 UTC

**Comment by sizhky** [comment] 2020-11-03 08:27
I got the same error for a simple notebook with only two cells. This notebook was present at `nbs/pdf_class.ipynb`

![image](https://user-images.githubusercontent.com/3656100/97962960-35f21400-1ddc-11eb-9bc8-a8a37980546b.png)

Following was the output and trace when I ran below code outside `nbs` folder
```python
from nbdev.export import *
notebook2script()
```

```python
Converted pdf_class.ipynb.
No export destination, ignored:
#export
import cv2
def get_registered_page(img, template):
    "register `img` into the coordinates of `template` "
    akaze = cv2.AKAZE_create()
    kpoints, des1 = akaze.detectAndCompute(template, None)
    kp1 = []
    for point in kpoints:
        temp = cv2.KeyPoint(x=point[0][0],y=point[0][1],_size=point[1], _angle=point[2], _response=point[3], _octave=point[4], _class_id=point[5])
        kp1.append(temp)
    kp2, des2 = akaze.detectAndCompute(img, None)
    matches = get_matches(kp2,des2,template)[2]
    ref_matched_kpts = np.float32([kp1[m[0].queryIdx].pt for m in matches])
    sensed_matched_kpts = np.float32([kp2[m[0].trainIdx].pt for m in matches])
    H, status = cv2.findHomography(sensed_matched_kpts, ref_matched_kpts, cv2.RANSAC,5.0)
    warped_image = cv2.warpPerspective(img, H, (img.shape[1], img.shape[0]))
    warped_image = warped_image[0:template_height,0:template_width]
    return warped_image
Warning: Exporting to "None.py" but this module is not part of this build
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-6ff9d98e6966> in <module>
      1 from nbdev.export import *
----> 2 notebook2script()

/conda/envs/rapids/lib/python3.6/site-packages/nbdev/export.py in notebook2script(fname, silent, to_dict)
    411     d = collections.defaultdict(list) if to_dict else None
    412     modules = create_mod_files(files, to_dict)
--> 413     for f in sorted(files): d = _notebook2script(f, modules, silent=silent, to_dict=d)
    414     if to_dict: return d
    415     else: add_init(Config().path("lib_path"))

/conda/envs/rapids/lib/python3.6/site-packages/nbdev/export.py in _notebook2script(fname, modules, silent, to_dict)
    349         code = _from_future_import(fname_out, flags, code, to_dict)
    350         if a:
--> 351             if to_dict is None: _add2all(fname_out, [f"'{f}'" for f in names if '.' not in f and len(f) > 0] + extra)
    352         mod.index.update({f: fname.name for f in names})
    353         code = re.sub(r' +$', '', code, flags=re.MULTILINE)

/conda/envs/rapids/lib/python3.6/site-packages/nbdev/export.py in _add2all(fname, names, line_width)
    204 def _add2all(fname, names, line_width=120):
    205     if len(names) == 0: return
--> 206     with open(fname, 'r', encoding='utf8') as f: text = f.read()
    207     tw = TextWrapper(width=120, initial_indent='', subsequent_indent=' '*11, break_long_words=False)
    208     re_all = _re__all__def.search(text)

FileNotFoundError: [Errno 2] No such file or directory: '/rapids/notebooks/atcdata/OCR/data/provider-enrollment/2Nov/imreg/None.py'
```

**Comment by sizhky** [comment] 2020-11-03 08:30
@DmitriyG228 I got the same error. You will have to create a #default_exp variable if the notebook contains an #export cell
