### ISSUE TITLE
`nbdev_new` fails due to uncleaned notebooks

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev#1311] opened 2023-03-12 19:11 UTC
```
no changes added to commit (use "git add" and/or "git commit -a")
[521](https://github.com/USER/REPO/actions/runs/4398996689/jobs/7703235848#step:2:533)
!!! Detected unstripped out notebooks
[522](https://github.com/USER/REPO/actions/runs/4398996689/jobs/7703235848#step:2:534)
!!!Remember to run nbdev_install_hooks
[523](https://github.com/USER/REPO/actions/runs/4398996689/jobs/7703235848#step:2:535)
+ echo -e '!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks'
[524](https://github.com/USER/REPO/actions/runs/4398996689/jobs/7703235848#step:2:536)
+ false
[525](https://github.com/USER/REPO/actions/runs/4398996689/jobs/7703235848#step:2:537)
Error: Process completed with exit code 1.
```

**Comment by dsm-72** [comment] 2023-03-13 12:53
I also have `pre-commit-hooks` installed and they _succeed_:

```yml
repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
  - id: nbdev_clean
  - id: nbdev_export
 ```

so why would these pass and GitHub fail?

**Comment by perceptualrobots** [comment] 2023-03-14 22:45
I have been getting a similar problem for a couple of weeks with errors on github. I have run nbdev_install_hooks a number of times.

```
+ git status -uno
+ echo -e '!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks'
On branch master
+ false
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   nbs/00_examples.ipynb
	modified:   nbs/01_putils.ipynb
	modified:   nbs/02_functions.ipynb
	modified:   nbs/03_nodes.ipynb
	modified:   nbs/04_hierarchy.ipynb
	modified:   nbs/05_environments.ipynb
	modified:   nbs/06_structure.ipynb
	modified:   nbs/07_errors.ipynb
	modified:   nbs/08_architectures.ipynb
	modified:   nbs/09_plotting.ipynb
	modified:   nbs/10_webots.ipynb
	modified:   nbs/11_network.ipynb
	modified:   nbs/index.ipynb

no changes added to commit (use "git add" and/or "git commit -a")
!!! Detected unstripped out notebooks
!!!Remember to run nbdev_install_hooks
Error: Process completed with exit code 1.
```

**Comment by fligt** [comment] 2023-03-15 11:41
I also experience the same problem with this error in my nbdev repositories when pushing to github. I am using nbdev version 2.3.11 in Anaconda Python 3.7.  

Steps to reproduce: 

1) created an empty github repository (https://github.com/fligt/testtest) and cloned to my machine 
2) created contents with `nbdev_new` 
3) Minor edits in 00_core.ipynb 
4) Installed hooks with `nbdev_install_hooks` 
5) Locally cleaned, tested and exported with `nbdev_prepare` with success.
6) Staged, committed and pushed to github with: 
    `git add -A`
    `git commit -m "first commit" `
   `git push`  

In github actions deploying to gh-pages with `deploy.yaml` succeeds, but `test.yaml` fails: 

```
...
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   nbs/00_core.ipynb
	modified:   nbs/index.ipynb

no changes added to commit (use "git add" and/or "git commit -a")
!!! Detected unstripped out notebooks
!!!Remember to run nbdev_install_hooks
Error: Process completed with exit code 1.
``` 
Does anyone have any idea what is causing this? I would think that the notebooks are clean when I push them. It seems that running `nbdev_clean` in the test is unexpectedly modifying the notebooks.

**Comment by dsm-72** [comment] 2023-03-15 13:04
Not sure what is causing it. I can literally new repos and sometimes it works, sometimes it doesnt. I have the same setup across a few projects and it works fine on 3/5 of them.

**Comment by nicole-brewer** [comment] 2023-03-20 05:25
This happens to me simply when initializing a repo created with `nbdev_new`

**Comment by fligt** [comment] 2023-03-21 22:58
Did some testing and found the cause of the github actions CI test failing!  

The problem is related to the kernelspec in the notebook json, which could look like below. 

```
"metadata": {
  "kernelspec": {
   "display_name": "Python (3)",
   "language": "python",
   "name": "python3"
  }
``` 
Note  here that the kernelspec `display_name` will typically differ form the kernelspec `name`. If you are **locally** cleaning you notebooks with any **older** version of nbdev, i.e. prior to current latest version 2.3.12 , cleaning the meta data **will not modify** the kernelspec.  

On the contrary, due to a recent code change in nbdev version 2.3.12, clean.py  (see: e47162f  and *fix issue* #995  *Make nb meta display_name consistent with name to simplify diffs*), the latest version of `nbdev_clean` **will modify** the `display_name` value to match the `name` value like so: 

```
"metadata": {
  "kernelspec": {
   "display_name": "python3",
   "language": "python",
   "name": "python3"
  }
``` 

Because github actions CI-test installs the latest version and executes nbdev_clean, this modifies the kernelspec in the notebooks where `display_name` and `name` do not match. Github actions test then reports that they notebooks were not properly cleaned before pushing, suggesting that github hooks were not installed.  

Simple fix is to update your local nbdev to the latest version 2.3.12. However this might not be obvious to many users that do not expect do need to update. I agree with [hyunjongkimmath](https://github.com/hyunjongkimmath) that it would be a good idea to include in the CI-test an error message to suggest upgrading nbdev #1308.

**Comment by dsm-72** [comment] 2023-03-21 23:06
@fligt hmm I'll try to reproduce. I thought it might be something like this but I figured since I have an environment with `nbdev` pinned at `2.3.12` and was still getting the issue I was unsure what it would be.

**Comment by fligt** [comment] 2023-03-21 23:26
@dsm-72, curious to hear the result of your tests. I used a text editor the try different kernelspec variations and see the effects of cleaning and pushing. I was expecting possible interference from other environmental factors but could not find any.

**Comment by perceptualrobots** [comment] 2023-03-22 17:13
> Simple fix is to update your local nbdev to the latest version 2.3.12. However this might not be obvious to many users that do not expect do need to update. I agree with [hyunjongkimmath](https://github.com/hyunjongkimmath) that it would be a good idea to include in the CI-test an error message to suggest upgrading nbdev #1308.

Thanks! It worked for me.

**Comment by seeM** [comment] 2023-04-27 11:12
Sorry for the confusion here! @fligt's [comment](https://github.com/fastai/nbdev/issues/1311#issuecomment-1478703113) diagnosing the issue is spot on.

This specific issue should be addressed by https://github.com/fastai/nbdev-template/commit/cf4a8c6318aa5ac4a7ea6035e306bf5287bfedee. Also see [this forum post](https://forums.fast.ai/t/failed-github-ci-when-following-end-to-end-walkthrough/104442/16?u=seem) for fixes to related issues.

**Closed by seeM** 2023-04-27 11:12 UTC
Labels: bug
