### ISSUE TITLE
No `nbdev_deploy` command

### ISSUE THREAD

**Issue by chrisagblake** [fastai/nbdev#1237] opened 2022-12-01 19:41 UTC
I would like to deploy my docs to GitHub Pages.

I can build them fine and preview with `nbdev_docs` and `nbdev_preview`. However I can't deploy as there is no `nbdev_deploy` command. It's not in the list of available commands when I run `nbdev_help`.

This is a private repo, however I do have a paid GitHub subscription which allows Pages on private repos. I have setup my Pages config to deploy from the `master` branch of my repo. I changed to the paid GitHub subscription after I setup the nbdev repo so it seems like nbdev thinks I don't have the option to deploy the docs so the command isn't available. How to I update nbdev to be able to deploy the docs?

Thanks

**Comment by deven367** [comment] 2023-01-15 14:12
@chrisagblake what version of nbdev are you using?

**Comment by chrisagblake** [comment] 2023-01-15 19:08
I realised it was because I had a newer version of nbdev than I had used previously and the latest version doesn't include the `nbdev_deploy` command but does it all through github actions. Thanks

**Comment by deven367** [comment] 2023-01-15 21:11
If the issue is resolved, can you please close the issue?

**Closed** 2023-01-15 21:15 UTC
