### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by nmoran** [fastai/nbdev#131] opened 2020-04-12 21:30 UTC
Think it would be useful to tag commits from which releases are created to make browsing the code easier. Is there a specific reason not to do this?

**Comment by sgugger** [comment] 2020-04-13 12:32
It's just not automated. Could be a nice feature to add to the automatic MakeFile generated by nbdev.

**Comment by sgugger** [comment] 2020-04-15 12:10
I'll close the issue as it's not a bug (and we keep issues for those only). Please post on the forum for the feature request (having nbdev automatically generate a MakeFile that does the tags with `make release`). I've also added it to my TODO for when I have some time but this will probably not be for a while.

**Closed by sgugger** 2020-04-15 12:10 UTC

**Comment by nmoran** [comment] 2020-04-15 19:12
Thanks. If I get a chance to attempt to implement this myself I'll open a pull request.
