### ISSUE TITLE
Enable GitHub Pages to publish from the root of the `gh-pages` branch

### ISSUE THREAD

**Issue by thigm85** [fastai/nbdev#1199] opened 2022-11-03 17:36 UTC
Got the following “Please enable Github pages” error today from [this repo](https://github.com/vespa-engine/learntorank):

![gh-pages-issue](https://user-images.githubusercontent.com/2162939/199793938-efefd72a-ef20-4ac8-b881-5f8c9912c2cd.png)

It was working fine before, and there was no gh-pages changes from my side as you can see in the pic below:

![Skjermbilde 2022-11-03 kl  14 34 25](https://user-images.githubusercontent.com/2162939/199793858-1fa995db-506e-4bb6-aea4-ab55e6c82128.png)

Here is the GitHub Actions link: [Merge pull request #17 from vespa-engine/tgm/time-query-operator · vespa-engine/learntorank@580448d · GitHub](https://github.com/vespa-engine/learntorank/actions/runs/3361561290/jobs/5576080906)

**Comment by hamelsmu** [comment] 2022-11-04 22:28
@thigm85 I am not able to reproduce this error on [my fork of the same repo](https://github.com/hamelsmu/learntorank)

https://hamelsmu.github.io/learntorank/

Do you think this could be a temporary issue, if it was working fine before, can you try deploying docs again?

**Comment by hamelsmu** [comment] 2022-11-04 22:31
One more thing to try, since I seen that it has been consistently failing on your repo is to disable github pages and re-enable it.  I have found that in the past this has gotten me unstuck from this scenario.  I don't have access to your repo's admin settings otherwhise I would try to fix it for you!  Please try this and LMK how it goes

**Comment by hamelsmu** [comment] 2022-11-04 22:58
Ok!  a similar error appears to be happening on new nbdev repos, possibly with changes to the GitHub API 

https://github.com/hamelsmu/new_nbdev2/actions/runs/3397589477/jobs/5649886520

Indeed, the message "resource not accessible by integration" suggests that the GitHub Actions Token can no longer enable GitHub pages automatically!  This is a bit different than the error message that you got "not found" and that I also got on my fork of the same repo https://github.com/hamelsmu/learntorank/actions/runs/3397552202/jobs/5649813434#step:2:621

Will update this comment with notes as I investigate the issue

**Comment by hamelsmu** [comment] 2022-11-04 23:15
I've verified that I can deploy docs again https://github.com/hamelsmu/learntorank/actions/runs/3397662467, so I'll go ahead and close this issue.  

You should be able to successfully deploy if you update your docs again.  

I can see your docs on my fork here: https://hamelsmu.github.io/learntorank/

**Closed by hamelsmu** 2022-11-04 23:15 UTC

**Comment by thigm85** [comment] 2022-11-05 11:06
Great, it now works. Thanks, @hamelsmu.
