### ISSUE TITLE
I cannot get pip nbdev working; coroutine was never awaited

### ISSUE THREAD

**Issue by kai-tub** [fastai/nbdev#454] opened 2021-04-07 14:38 UTC
To reproduce:
```bash
conda create --name=nbdev_bug python=3.8
conda activate nbdev_bug
pip install nbdev
nbdev_test_nbs
```
returns
```
[...]
RuntimeWarning: coroutine 'ZMQSocketChannel.get_msg' was never awaited
  return False,time.time()-start
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
Test run on the `nbs` folder of this repository.

**Comment by kai-tub** [comment] 2021-04-07 14:41
Also doesn't work with Python 3.9
Maybe a dependency changed?

**Comment by kai-tub** [comment] 2021-04-07 14:53
If this is true, maybe simply rerunning the CI/CD pipeline will return an error?

**Comment by kai-tub** [comment] 2021-04-07 14:58
Yes, as I've thought some underlying dependency must've changed/broken.
See my dummy PR #455 which simply restarts the pipeline.
All tests fail with the error message I was getting.

**Comment by kai-tub** [comment] 2021-04-07 15:05
Output of `pip freeze` after installing from master branch:
```
argon2-cffi==20.1.0
attrs==20.3.0
backcall==0.2.0
bleach==3.3.0
certifi==2020.12.5
cffi==1.14.5
decorator==5.0.5
defusedxml==0.7.1
entrypoints==0.3
fastcore==1.3.19
fastrelease==0.1.11
ghapi==0.1.16
ipykernel==5.5.3
ipython==7.22.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==2.11.3
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.13
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyterlab-widgets==1.0.0
MarkupSafe==1.1.1
mistune==0.8.4
nbconvert==5.6.1
nbdev @ file:///home/kaiclasen/nbdev/nbdev
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.3.0
packaging==20.9
pandocfilters==1.4.3
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.10.0
prompt-toolkit==3.0.18
ptyprocess==0.7.0
pycparser==2.20
Pygments==2.8.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
PyYAML==5.4.1
pyzmq==22.0.3
qtconsole==5.0.3
QtPy==1.9.0
Send2Trash==1.5.0
six==1.15.0
terminado==0.9.4
testpath==0.4.4
tornado==6.1
traitlets==5.0.5
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
```

**Comment by kai-tub** [comment] 2021-04-07 15:56
My current guess is:
`jupyter_client-6.1.13` as it was updated 8h ago. 
Which would be exactly when I first saw the issue in my pipeline

**Comment by kai-tub** [comment] 2021-04-07 16:03
Yes! 
This is definitely the issue.
Filing a bug report, but it would be helpful if somebody with deeper knowledge could provide more information about what is breaking.

**Comment by hamelsmu** [comment] 2021-04-07 16:30
I cannot reproduce this error.  Since I'm not the one experiencing the error, (you are) I would suggest that you file the bug report on the appropriate project.  

Also nbdev doesn't yet support Python 3.9

**Comment by kai-tub** [comment] 2021-04-07 16:42
I understand.
But you _can_ reproduce the error.
At least the CI pipeline was able to reproduce it/shows the broken code.
So also every PR/update to this project will break due to the bug in the library.

**Comment by hamelsmu** [comment] 2021-04-07 17:30
Oh I see you are correct.  I was confused by the wording of this issue!  This is indeed a problem.

**Comment by hamelsmu** [comment] 2021-04-07 17:31
Closing this issue in favor of #456

**Closed by hamelsmu** 2021-04-07 17:31 UTC
