### ISSUE TITLE
`nbdev_export` does not export functions to none-default python module

### ISSUE THREAD

**Issue by BirkhoffG** [fastai/nbdev#958] opened 2022-08-29 22:31 UTC
nbdev version: v2.2.8

I want to export a function to a python module other than the `default_exp`. In nbdev v1, it can be achieved by `# export [python_module]`.

However, I cannot do the same in v2.

### To reproduce my error

My code repo: https://github.com/BirkhoffG/cfnet/tree/344a29ba4aed065abb3337ab45599e4b20b1927d

1. I want to export `make_model` and `init_net_opt` written in `nbs/03_training_module.ipynb` into `cfnet/utils.py`.
2. `nbdev_export`
3. These functions are not exported to the desired locations (i.e., `cfnet/utils.py`).

**Comment by jph00** [comment] 2022-08-29 23:02
Dupe of #742

**Closed by jph00** 2022-08-29 23:02 UTC
