### ISSUE TITLE
exported symbols deleted if two notebooks share #default_exp

### ISSUE THREAD

**Issue by jerzydziewierz** [fastai/nbdev#1034] opened 2022-09-11 17:27 UTC
**Environment:**
a repo after initialization with nbdev

**Steps to reproduce**

start a repo, say, `example`. 

* In notebook 1, add:
```python
#|default_exp core
#export 
def hello1():
   print('hello1')
import nbdev; nbdev.nbdev_export()
```

In notebook 2, add:
```python
#|default_exp core
#export 
def hello2():
   print('hello2')
import nbdev; nbdev.nbdev_export()
```

Then, 

in python console or yet another notebook, say:
```python
import example.core
dir(example.core)
```

**observed result**

No error message, and the `example.core` module contains only one method, `hello2()`. Method `hello1()` is nowhere to be found. 

** Expected result:
either:

(a) an error on running `nbdev_export()` saying that there are two notebooks with the same export target

OR

(b) The `example.core.*` module contains methods from both notebooks. If there are **any** symbol redefinitions anywhere, a warning message is issued. 

**analysis**

The (b) would appear to be preferable at first; however, it quickly runs into the problem of additional confusion created by redefining the methods already defined, without errors. It will be no problem for seasoned developers to know about such a quirk; for beginners, the approach (a) would give less risk of confusion.

**Comment by jph00** [comment] 2022-09-11 21:23
dupe of #987

**Closed by jph00** 2022-09-11 21:23 UTC
