### ISSUE TITLE
DataFrame Output Representation

### ISSUE THREAD

**Issue by AyrtonB** [fastai/nbdev#345] opened 2020-12-21 13:44 UTC
Currently there's an issue with the output from dataframes where they're stored as html which leads to issues in documentation generation, e.g. overlapping with contents.

![image](https://user-images.githubusercontent.com/29051639/102781405-8541d300-438f-11eb-86d3-badb0b480f58.png)

Example subset of the markdown file:

```
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>sett_bmu_id</th>
      <th>ngc_bmu_id</th>
      <th>bmu_root</th>
      <th>name</th>
      <th>primary_fuel_type</th>
      <th>detailed_fuel_type</th>
      <th>longitude</th>
      <th>latitude</th>
      <th>common_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>E_MARK-1</td>
      <td>MARK-1</td>
      <td>MARK</td>
      <td>Rothes Bio-Plant CHP 1</td>
      <td>biomass</td>
      <td>bone</td>
      <td>-3.603516</td>
      <td>57.480403</td>
      <td>Rothes Bio-Plant CHP</td>
    </tr>
    <tr>
      <th>1</th>
      <td>E_MARK-2</td>
      <td>MARK-2</td>
      <td>MARK</td>
      <td>Rothes Bio-Plant CHP 2</td>
      <td>biomass</td>
      <td>bone</td>
      <td>-3.603516</td>
      <td>57.480403</td>
      <td>Rothes Bio-Plant CHP</td>
    </tr>
  </tbody>
</table>
</div>
```

<br>

Changing this to a markdown table fixes these issues

![image](https://user-images.githubusercontent.com/29051639/102782267-fafa6e80-4390-11eb-86ff-db71468551c9.png)

They also have the advantage of the raw files being more readable in GitHub.

```
|    | sett_bmu_id   | ngc_bmu_id   | bmu_root   | name                   | primary_fuel_type   | detailed_fuel_type   |   longitude |   latitude | common_name          |
|---:|:--------------|:-------------|:-----------|:-----------------------|:--------------------|:---------------------|------------:|-----------:|:---------------------|
|  0 | E_MARK-1      | MARK-1       | MARK       | Rothes Bio-Plant CHP 1 | biomass             | bone                 |    -3.60352 |    57.4804 | Rothes Bio-Plant CHP |
|  1 | E_MARK-2      | MARK-2       | MARK       | Rothes Bio-Plant CHP 2 | biomass             | bone                 |    -3.60352 |    57.4804 | Rothes Bio-Plant CHP |
|  2 | T_DIDC1       | DIDC1        | DIDC       | Didcot A (G) 1         | coal                | coalgas_opt_out      |    -1.26757 |    51.6236 | Didcot A (G)         |
|  3 | T_DIDC2       | DIDC2        | DIDC       | Didcot A (G) 2         | coal                | coalgas_opt_out      |    -1.26757 |    51.6236 | Didcot A (G)         |
|  4 | T_DIDC4       | DIDC4        | DIDC       | Didcot A (G) 4         | coal                | coalgas_opt_out      |    -1.26757 |    51.6236 | Didcot A (G)         |
```

<br>

I started testing some things out which could clean up the files after running `convert_md` and made some progress, however I was unable to generalise it sufficiently to handle edge cases where people may want to have a HTML table. I used `BeautifulSoup` and `pandas` to identify the tables and carry out the conversions, however replacing the correct tables (including the parent div and styling) was more difficult. The main reason for this is that the string created from the soup doesn't exactly match with the raw HTML table, meaning it can't be easily replaced.

My hunch is that a complex regex could extract the table sections directly from the markdown (avoiding the HTML conversion and bs4 processes) and then converted using pandas. I don't know enough regex to handle this myself though. If anyone knows how i could get the regex working I'm happy to try and implement the rest in a PR.

N.b. All dataframe outputs include `class="dataframe"` which would enable other user generated tables to be ignored

**Comment by AyrtonB** [comment] 2020-12-21 17:51
Not elegant but this works. Where's the best place to apply it within the existing nbdev codebase?

```python
import os
import pandas as pd
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.tags = []
    
    def handle_starttag(self, tag, attrs):
        self.tags.append(self.get_starttag_text())

    def handle_endtag(self, tag):
        self.tags.append(f"</{tag}>")
        
get_substring_idxs = lambda string, substring: [num for num in range(len(string)-len(substring)+1) if string[num:num+len(substring)]==substring]

def convert_df_to_md(df):
    idx_col = df.columns[0]
    df = df.set_index(idx_col)
    
    if idx_col == 'Unnamed: 0':
        df.index.name = ''
    
    table_md = df.to_markdown()
    
    return table_md

def extract_div_to_md_table(start_idx, end_idx, table_and_div_tags, file_txt):
    n_start_divs_before = table_and_div_tags[:start_idx].count('<div>')
    n_end_divs_before = table_and_div_tags[:end_idx].count('</div>')

    div_start_idx = get_substring_idxs(file_txt, '<div>')[n_start_divs_before-1]
    div_end_idx = get_substring_idxs(file_txt, '</div>')[n_end_divs_before]

    div_txt = file_txt[div_start_idx:div_end_idx]
    potential_dfs = pd.read_html(div_txt)
    
    assert len(potential_dfs) == 1, 'Multiple tables were found when there should be only one'
    df = potential_dfs[0]
    md_table = convert_df_to_md(df)

    return div_txt, md_table

def extract_div_to_md_tables(md_fp):
    with open(md_fp, 'r') as f:
        file_txt = f.read()
        
    parser = MyHTMLParser()
    parser.feed(file_txt)

    table_and_div_tags = [tag for tag in parser.tags if tag in ['<div>', '</div>', '<table border="1" class="dataframe">', '</table>']]
    
    table_start_tag_idxs = [i for i, tag in enumerate(table_and_div_tags) if tag=='<table border="1" class="dataframe">']
    table_end_tag_idxs = [table_start_tag_idx+table_and_div_tags[table_start_tag_idx:].index('</table>') for table_start_tag_idx in table_start_tag_idxs]

    div_to_md_tables = []

    for start_idx, end_idx in zip(table_start_tag_idxs, table_end_tag_idxs):
        div_txt, md_table = extract_div_to_md_table(start_idx, end_idx, table_and_div_tags, file_txt)
        div_to_md_tables += [(div_txt, md_table)]
        
    return div_to_md_tables

def clean_md_file_tables(md_fp):
    div_to_md_tables = extract_div_to_md_tables(md_fp)
    
    with open(md_fp, 'r') as f:
        md_file_text = f.read()

    for div_txt, md_txt in div_to_md_tables:
        md_file_text = md_file_text.replace(div_txt, md_txt)

    with open(md_fp, 'w') as f:
        f.write(md_file_text)
        
    return 
```

**Comment by hamelsmu** [comment] 2020-12-23 18:56
Hello, I cannot reproduce this issue with nbdev.

![image](https://user-images.githubusercontent.com/1483922/103028524-cb707100-450c-11eb-9854-f19b4ce00f1d.png)

My suspicion is there is something about your theme (I noticed you are using a different theme than what nbdev is tested on, so perhaps there is something in your theme that is causing this problem ?).  

Either way, I'm not able to reproduce this issue.  If you think this could be an issue still, if you don't mind open an issue with a reproducible example that does something that breaks with the native theme?

I can imagine though that a scrollbar for overflow may be desired, but if that is the case, perhaps that should be a separate issue.  Closing this for now, but please do follow up if appropriate.  

Thanks!

**Closed by hamelsmu** 2020-12-23 18:56 UTC
