### ISSUE TITLE
Help Using `notebook2html`

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#38] opened 2020-01-08 19:41 UTC
I am trying to use `notebook2html` by itself.  I'm confused because I'm able to import the library just fine

`from nbdev.export2html import notebook2html`

However, getting a strange error regarding `ModuleNotFoundError` when trying to call `notebook2html` in an ipython console.  Perhaps its something to do with the way nbdev is being called but I'm not sure?  

```console
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from nbdev.export2html import notebook2html

In [2]: notebook2html('1-altair_introduction.ipynb')
converting: 1-altair_introduction.ipynb
An error occurred while executing the following cell:
------------------
#export
from nbdev.showdoc import show_doc
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5f00178d23a7> in <module>()
      1 #export
----> 2 from nbdev.showdoc import show_doc

ModuleNotFoundError: No module named 'nbdev'
ModuleNotFoundError: No module named 'nbdev'
```

**Comment by sgugger** [comment] 2020-01-08 20:47
That is weird indeed. So this error comes because `notebook2html` executes all the cells with `show_doc(function_or_class)` (that are automatically added in place of exported code cells). For this to work, it adds a cell `from nbdev.showdoc import show_doc` at the top of the notebook, which for some reason is failing.
My best guess would be that the environment in which nbconvert executes the notebook does not have nbdev installed, but I have no idea how to fix it.

**Comment by hamelsmu** [comment] 2020-01-08 21:08
Thanks @sgugger are you able to reproduce this error?  If not, that might at least start giving me hints on how to proceed.  

Interestingly, I am not calling `showdoc` anywhere in my notebook, but not sure that matters in this case. 

I tried installing nbdev in my global environment but that didn't help. 

BTW How do you generate blog posts for the main fast.ai website from Jupyter Notebooks, do you call this function this way?

**Comment by sgugger** [comment] 2020-01-08 21:13
No I haven't been able to reproduce that bug. In ipython, your code works fine for me.
It doesn't matter if you code doesn't call `show_doc`. Each time you define a function that is exported, the command `notebook2html` will replace it by a show_doc cell before converting to HTML.

To generate blog posts, we use the command `nbdev_nb2md`.

**Comment by hamelsmu** [comment] 2020-01-08 21:42
Thanks @sgugger I was able to make this work inside a Docker container, so maybe something funky with my local environment?  Should I close this issue?  Thanks for the insights

**Comment by sgugger** [comment] 2020-01-08 21:45
Glad you managed to get it to work. Probably an env issue yes. Let's close this, but please reopen if you find a reproducible way of getting the bug!

**Closed by sgugger** 2020-01-08 21:45 UTC
